name: Swift

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    name: swift-test
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: Download and run MeiliSearch
      run:  brew update && brew install meilisearch
    - name: Run MeiliSearch
      run: meilisearch --no-analytics=true --master-key=masterKey &
    - name: Run tests
      run: swift test -v
